name: Daily Commit

on:
  schedule:
    - cron: "30 0 * * *"  # Runs daily at 00:30 UTC
  workflow_dispatch:  # Allows manual triggering

jobs:
  commit:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Generate timestamp file
        run: echo "$(date)" > last_run.txt

      - name: Commit changes (22f2001630@ds.study.iitm.ac.in)
        run: |
          git config --local user.name "GitHub Actions Bot"
          git config --local user.email "22f2001630@ds.study.iitm.ac.in"
          git add last_run.txt
          git commit -m "Automated commit: $(date)" || exit 0
          git push
